//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_thuedocuoi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        public SANPHAM()
        {
            this.CHITIETDHs = new HashSet<CHITIETDH>();
            this.KIEMTRASPs = new HashSet<KIEMTRASP>();
        }
    
        public string MASP { get; set; }
        public string TENSP { get; set; }
        public string HINHANH { get; set; }
        public decimal GIA { get; set; }
        public Nullable<int> SOLUONGTON { get; set; }
        public string MOTA { get; set; }
        public string MA_DANHMUC { get; set; }
    
        public virtual ICollection<CHITIETDH> CHITIETDHs { get; set; }
        public virtual DANHMUCSP DANHMUCSP { get; set; }
        public virtual ICollection<KIEMTRASP> KIEMTRASPs { get; set; }
    }
}
